# -*- coding: utf-8 -*-
"""Untitled1py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sDO9gsb-7IScvZIWNMhXQ_ca20Xg6rBY
"""

# app.py
def add(a, b):
  return a + b
  if __name__ == "__main__":
    print(f"2 + 3 = {add(2, 3)}")