# -*- coding: utf-8 -*-
"""Untitled py .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13rYe6XzyWlm_RWTBoOgltmhSB1p-MGhy
"""

# test_app.py
from app import add
def test_add():
  assert add(2, 3) ==