# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135pD3ieYurC94N7K-MpJfft1eBdZu3xO
"""

# requirements.txt
pytest